---

- name: main.yml | Create "{{ traefik_config_dir }}"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_config_dir }}"

- name: main.yml | Download and install Traefik in "{{ traefik_install_dir }}"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - url: "{{ traefik_binary_url }}"
      dest: "{{ traefik_bin_path }}"

- name: main.yml | Template Traefik config and unit
  template:
    src: "{{ item }}.j2"
    dest: "{{ traefik_config_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - traefik.toml
    - rules.toml
    - unit
  notify: restart traefik
  tags: traefik_config
