---
- name: main.yml | Create {{ traefik_config_dir }}
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_config_dir }}"

- name: main.yml | Download Traefik
  get_url:
    url: "{{ traefik_binary_url }}"
    dest: "/tmp"
    owner: root
    group: root
    mode: 0755
  when: traefik_binary_url is defined

- name: main.yml | Unarchive {{ traefik_install_dir }}
  unarchive:
    src: "{{ traefik_archive_url }}"
    dest: "{{ traefik_install_dir }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  when: traefik_archive_url is defined

- name: main.yml | Add exec bit to "{{ traefik_binary_url }}"
  file:
    path: "{{ traefik_bin_path }}"
    mode: "0755"

- name: main.yml | Template Traefik config and unit
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: traefik.yml.j2, dest: "{{ traefik_config_dir }}/traefik.yml", mode: '0755' }
    - { src: dynamic.yml.j2, dest: "{{ traefik_config_dir }}/dynamic.yml", mode: '0755' }
    - { src: unit.j2, dest: /etc/systemd/system/traefik.service, mode: '0644'}
  notify: restart traefik
  tags: traefik_config

- name: main.yml | Force systemd to reread configs
  systemd: 
    daemon_reload: yes

- name: main.yml | Enable unit service and ensure it is not masked
  systemd: 
    name: traefik.service 
    enabled: yes 
    masked: no 
    state: started
